-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."emails" add column "isVerified" boolean
--  null default 'false';
