-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."question_options" add column "is_correct" bool
--  null default 'false';
